import type { ModuleDefinition } from "../moduleConfigTypes";
import { numericScaleOptions, singleSelectOptions } from "./questionHelpers";

export const identityModule: ModuleDefinition = {
  slug: "identity",
  displayTitle: "The Identity Lens",
  aiShortName: "Identity Lens",
  headline: "Who you believe you are shapes everything else",
  sub: "This goes deeper than roles or responsibilities. These 8 questions look at the beliefs underneath your behavior.",
  sensitivityTier: "standard",
  presentationCopy: "Go deeper: who you believe you are shapes everything else",
  defaultUnlockDay: 7,
  completeFlagColumn: "moduleIdentityComplete",
  onboardingCompleteFlag: "module_identity_complete",
  estimatedMinutes: 10,
  sideEffects: [],
  questions: [
    {
      id: "iq1",
      prompt: "Where does most of your sense of self-worth come from right now?",
      kind: "single_select",
      fieldKey: "identitySelfWorthSource",
      options: singleSelectOptions([
        { slug: "performance_based", label: "What I achieve — my worth tracks with my output and results" },
        { slug: "approval_based", label: "How others see me — I feel good about myself when I'm validated by others" },
        { slug: "inherent", label: "Who I am — my worth doesn't change based on what I do or what others think" },
        { slug: "unclear", label: "I'm not sure — it shifts or I haven't thought about it this way before" },
      ]),
    },
    {
      id: "iq2",
      prompt: "When you face a real setback, which internal story tends to take over?",
      kind: "single_select",
      fieldKey: "identityNarrativeType",
      options: singleSelectOptions([
        { slug: "growth", label: "This is information — I can learn from this and adjust how I move forward" },
        { slug: "fixed", label: "This confirms something I already believed about my limits" },
        { slug: "mixed", label: "It depends — sometimes I recover the narrative, sometimes I don't" },
        { slug: "unclear", label: "I'm not sure I'm aware of a consistent story when things go wrong" },
      ]),
    },
    {
      id: "iq3",
      prompt: "How much of your sense of identity is tied to your role — your job, title, or function?",
      kind: "numeric_scale",
      fieldKey: "identityRoleFusionScore",
      options: numericScaleOptions([
        "Very little — who I am feels separate from what I do",
        "Some — my role is part of me but not most of me",
        "Significant — my role is a major part of how I see myself",
        "Very high — I struggle to separate who I am from what I do",
        "Total — I don't know who I am outside of this role",
      ]),
    },
    {
      id: "iq4",
      prompt: "Where did the standards you hold yourself to originally come from?",
      kind: "single_select",
      fieldKey: "identityPressureOrigin",
      options: singleSelectOptions([
        { slug: "self_set", label: "I developed them myself — they reflect my own values and goals" },
        { slug: "family", label: "They came from my upbringing — often unstated but deeply felt expectations" },
        { slug: "culture", label: "They came from my environment — career norms, peers, or social comparison" },
        { slug: "survival", label: "They formed as a way to stay safe, be loved, or manage difficult circumstances" },
        { slug: "unclear", label: "I'm not sure — they're just the water I swim in" },
      ]),
    },
    {
      id: "iq5",
      prompt: "How easy is it for you to extend yourself the same compassion you'd offer a close friend who was struggling?",
      kind: "numeric_scale",
      fieldKey: null,
      options: numericScaleOptions([
        "Very hard — I'm much harsher with myself than I would ever be with someone I care about",
        "Difficult — I know I should but rarely actually do it",
        "Sometimes — I manage it in some situations but not others",
        "Often — I'm getting better at being kind to myself",
        "Fairly natural — I can treat myself with the same care I'd give others",
      ]),
    },
    {
      id: "iq6",
      prompt: "How loud is the voice in your head that criticizes, judges, or tells you you're not enough?",
      kind: "numeric_scale",
      fieldKey: null,
      options: numericScaleOptions([
        "Constant and loud — it's running most of the time",
        "Frequent — it shows up a lot, especially in hard moments",
        "Present but not dominant — I notice it but don't always believe it",
        "Occasional — it shows up sometimes but doesn't run the show",
        "Quiet — it's there but it rarely has real authority over how I see myself",
      ]),
    },
    {
      id: "iq7",
      prompt: "How comfortable are you existing without producing, achieving, or being useful?",
      kind: "numeric_scale",
      fieldKey: null,
      options: numericScaleOptions([
        "Very uncomfortable — rest or stillness feels wrong or unsafe",
        "Difficult — I can do it but there's guilt or anxiety underneath",
        "Mixed — some rest feels okay, other times I can't settle",
        "Fairly comfortable — I can be without doing without too much difficulty",
        "Comfortable — I value rest and presence as much as output",
      ]),
    },
    {
      id: "iq8",
      prompt: "When your sense of who you are is challenged — by failure, change, or someone's criticism — how do you respond?",
      kind: "numeric_scale",
      fieldKey: null,
      options: numericScaleOptions([
        "It destabilizes me significantly — I lose my footing and it takes a long time to recover",
        "It hits hard — I'm affected for a while before I can reorient",
        "It stings but I find my way back — it just takes effort",
        "I feel it but I'm able to reconnect with myself fairly quickly",
        "I stay relatively grounded — my sense of who I am doesn't depend on the outcome",
      ]),
    },
  ],
};
