import type { ModuleDefinition } from "../moduleConfigTypes";
import { numericScaleOptions, singleSelectOptions } from "./questionHelpers";

export const relationalModule: ModuleDefinition = {
  slug: "relational",
  displayTitle: "Your Relational Blueprint",
  aiShortName: "Relational Blueprint",
  headline: "How you connect — and how you protect yourself",
  sub: "These questions look at your patterns in relationships — not to judge them, but to understand how they're shaping what's possible for you.",
  sensitivityTier: "standard",
  presentationCopy: "Understand how you connect — and how you protect yourself",
  defaultUnlockDay: 14,
  completeFlagColumn: "moduleRelationalComplete",
  onboardingCompleteFlag: "module_relational_complete",
  estimatedMinutes: 10,
  sideEffects: [],
  questions: [
    {
      id: "rq1",
      prompt: "When a relationship feels uncertain or strained, your first instinct is usually to:",
      kind: "single_select",
      fieldKey: "attachmentSignal",
      options: singleSelectOptions([
        { slug: "anxious", label: "Reach out, seek reassurance, or try to resolve it quickly — uncertainty is hard to sit with" },
        { slug: "avoidant", label: "Create space and distance — I process better when I pull back" },
        { slug: "secure", label: "Stay present and address it when timing feels right — I trust it can work through" },
        { slug: "disorganized", label: "It varies unpredictably — sometimes I reach out, sometimes I shut down, often I don't know why" },
      ]),
    },
    {
      id: "rq2",
      prompt: "When real conflict arises with someone important to you, you tend to:",
      kind: "single_select",
      fieldKey: "conflictPattern",
      options: singleSelectOptions([
        { slug: "avoid", label: "Minimize it, change the subject, or let it go without real resolution" },
        { slug: "escalate", label: "Engage directly and sometimes more intensely than I intended" },
        { slug: "collapse", label: "Agree or apologize quickly to restore peace even when I don't mean it" },
        { slug: "engage", label: "Stay present with the discomfort and work toward actual resolution" },
      ]),
    },
    {
      id: "rq3",
      prompt: "When you're genuinely struggling, asking for help feels:",
      kind: "single_select",
      fieldKey: "supportSeekingCapacity",
      options: singleSelectOptions([
        { slug: "high", label: "Natural — I reach out and can receive support well" },
        { slug: "medium", label: "Possible but uncomfortable — I do it but it takes real effort" },
        { slug: "low", label: "Very difficult — I prefer to handle things alone or feel I shouldn't need help" },
        { slug: "blocked", label: "Almost impossible — asking for help feels like failure or significant risk" },
      ]),
    },
    {
      id: "rq4",
      prompt: "In your closest relationship right now — partner, best friend, or whoever is most significant — how emotionally safe do you feel?",
      kind: "single_select",
      fieldKey: "intimacySafetyLevel",
      options: singleSelectOptions([
        { slug: "safe", label: "Very safe — I can be fully myself without editing" },
        { slug: "mixed", label: "Mostly safe but with things I hold back or can't say" },
        { slug: "unsafe", label: "Mostly unsafe — I feel like I need to manage how I appear" },
        { slug: "absent", label: "This relationship doesn't exist right now — I don't have a primary close relationship" },
      ]),
    },
    {
      id: "rq5",
      prompt: "How lonely do you feel — not in terms of being alone, but in terms of being truly known by someone?",
      kind: "numeric_scale",
      fieldKey: null,
      options: numericScaleOptions([
        "Deeply lonely — I feel unseen even in the company of people who care about me",
        "Often lonely — the knowing feels surface-level in most of my relationships",
        "Sometimes — I have moments of real connection but they're not consistent",
        "Rarely — I feel known by at least a few people in my life",
        "Not lonely — I feel genuinely known and connected",
      ]),
    },
    {
      id: "rq6",
      prompt: "How well do you receive care, help, or support when it's offered to you?",
      kind: "numeric_scale",
      fieldKey: null,
      options: numericScaleOptions([
        "I deflect it, minimize it, or feel uncomfortable — receiving is hard for me",
        "I can receive it but there's discomfort or guilt underneath",
        "Mixed — depends on who it's from and what kind of support it is",
        "Fairly well — I can let people in without too much difficulty",
        "Well — I can receive care gracefully and it genuinely nourishes me",
      ]),
    },
    {
      id: "rq7",
      prompt: "How much do your relationships currently cost you versus nourish you?",
      kind: "numeric_scale",
      fieldKey: null,
      options: numericScaleOptions([
        "They cost much more than they give — I'm pouring out with very little coming back",
        "Mostly costly — I give a lot and feel somewhat depleted by my relationships",
        "About equal — some take, some give, it roughly balances",
        "Mostly nourishing — my relationships generally refuel me",
        "Very nourishing — the people in my life are a genuine source of strength",
      ]),
    },
    {
      id: "rq8",
      prompt: "How much do you believe you are worthy of deep, mutual, loving relationships?",
      kind: "numeric_scale",
      fieldKey: null,
      options: numericScaleOptions([
        "I struggle to believe that — somewhere I feel like I'm too much, not enough, or fundamentally unlovable",
        "I intellectually believe it but emotionally it's harder — part of me doubts it",
        "Most of the time I believe it, but it shakes in certain moments",
        "I generally believe it — I know I deserve real connection",
        "Fully — I know I am worthy of and capable of deep mutual love and connection",
      ]),
    },
  ],
};
