#!/usr/bin/env node
// ai-control.mjs — portable deterministic control plane for the two-chat PM<->coder flow.
//
// Source of truth = .ai/control/{tasks.json,events.jsonl,approvals.json,gates.json} (machine-written here).
// Generated views = .ai/{current-state,current-focus,tasks}.md (rendered by `sync`; never hand-edited)
//   + .ai/worklog.md GENERATED section BELOW a freeze marker (history ABOVE the marker is never touched).
// Authored files (PROJECT.md + any reference docs) are NEVER touched by this tool.
//
// Project specifics come from .ai/control/config.json (written by `init`) — this CLI carries NO
// project/company content. Windows + PowerShell friendly: pure Node, no bash. Run:
//   node .claude/tools/ai-control.mjs <command>
// Commands: init | status | sync | check | doctor | gate set <name> <pass>
//   | task create|ready|start|checkpoint|finish|accept|block|reopen|abandon|deliver

import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import {
  readFileSync, writeFileSync, renameSync, existsSync, mkdirSync, statSync,
} from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve, relative } from 'node:path';

const SCHEMA_VERSION = 1;
const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, '..', '..');
const AI_DIR = join(REPO_ROOT, '.ai');
const CONTROL_DIR = join(AI_DIR, 'control');

const F = {
  config: join(CONTROL_DIR, 'config.json'),
  tasks: join(CONTROL_DIR, 'tasks.json'),
  events: join(CONTROL_DIR, 'events.jsonl'),
  approvals: join(CONTROL_DIR, 'approvals.json'),
  gates: join(CONTROL_DIR, 'gates.json'),
};
const GEN = {
  state: join(AI_DIR, 'current-state.md'),
  focus: join(AI_DIR, 'current-focus.md'),
  tasks: join(AI_DIR, 'tasks.md'),
};
const WORKLOG = join(AI_DIR, 'worklog.md');
const PROJECT_MD = join(AI_DIR, 'PROJECT.md');
const GEN_HEADER =
  '<!-- GENERATED by ai-control · DO NOT EDIT · source: .ai/control/ · run: node .claude/tools/ai-control.mjs sync -->';
// Everything ABOVE this marker in worklog.md is FROZEN history — sync never touches it. Below is rendered
// from events.jsonl. The marker text is matched verbatim, so do not change it.
const WORKLOG_MARKER =
  '<!-- ai-control:generated below — DO NOT EDIT below this line. History above is frozen; ai-control sync renders new events here. -->';

const TASK_STATES = ['backlog', 'ready', 'in_progress', 'review', 'accepted', 'blocked', 'abandoned'];
const DELIVERY_STATES = ['uncommitted', 'committed', 'pushed', 'deployed'];

// ---------------------------------------------------------------- config (project specifics; NOT this CLI)
function loadConfig() {
  const defaults = {
    projectName: 'project', defaultBranch: 'main', codePaths: ['src'], hasDb: false, hasDeploy: false,
    ownerFilesNote: 'current truth → current-state.md · queue → tasks.md · active slice → current-focus.md · history → worklog.md',
  };
  try { if (existsSync(F.config)) return { ...defaults, ...JSON.parse(readFileSync(F.config, 'utf8')) }; }
  catch { /* fall back to defaults on a malformed config */ }
  return defaults;
}
function codePaths() { const c = loadConfig().codePaths; return Array.isArray(c) && c.length ? c : ['src']; }
function codePrefixes() { return codePaths().map((p) => (p.endsWith('/') ? p : `${p}/`)); }

// ---------------------------------------------------------------- git helpers
function git(args, { allowFail = true } = {}) {
  try {
    return execFileSync('git', args, { cwd: REPO_ROOT, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 }).trim();
  } catch (e) {
    if (allowFail) return '';
    throw e;
  }
}
const gitHead = () => git(['rev-parse', 'HEAD']);
const gitHeadShort = () => git(['rev-parse', '--short', 'HEAD']);
const gitTree = () => git(['rev-parse', 'HEAD^{tree}']);
const gitBranch = () => git(['rev-parse', '--abbrev-ref', 'HEAD']);
const short = (sha) => (sha ? String(sha).slice(0, 7) : '');

// Parse `git status --porcelain=v1 -z`. NUL-separated; rename/copy records carry a 2nd NUL token
// (the original path) which we consume and ignore. Returns [{ x, y, path }] (path forward-slashed).
function parsePorcelainZ(raw) {
  const out = [];
  const tokens = raw.split('\0');
  for (let i = 0; i < tokens.length; i++) {
    const t = tokens[i];
    if (t.length < 4) continue; // skip '' tail and malformed
    const x = t[0];
    const y = t[1];
    const path = t.slice(3).replace(/\\/g, '/');
    out.push({ x, y, path });
    if (x === 'R' || x === 'C') i++; // porcelain v1: original-path token follows an R/C INDEX status only
  }
  return out;
}

// Fingerprint the CODE change-set (staged + unstaged + untracked + deleted), scoped to the configured
// code paths, with per-file content hashes. Clean tree → bind to commit + tree.
function computeFingerprint() {
  const head = gitHead();
  const tree = gitTree();
  if (!head || !tree) return 'error:git-unavailable'; // a broken/empty git must NOT masquerade as a clean tree
  const paths = codePaths();
  const prefixes = codePrefixes();
  let raw;
  try {
    // -uall expands untracked DIRECTORIES into individual files (else git collapses a new folder into
    // one `?? dir/` record — the exact new-file-in-a-new-folder case the fingerprint must hash).
    raw = execFileSync('git', ['status', '--porcelain=v1', '-z', '-uall', '--', ...paths],
      { cwd: REPO_ROOT, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  } catch { return 'error:git-status-failed'; }
  const entries = parsePorcelainZ(raw)
    .filter((e) => prefixes.some((p) => e.path.startsWith(p)))
    .sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  if (entries.length === 0) return `clean:${head}:${tree}`; // clean / post-commit binding
  const h = createHash('sha256');
  for (const e of entries) {
    h.update(`${e.x}${e.y} ${e.path}\n`);
    const abs = join(REPO_ROOT, e.path);
    if (e.x === 'D' || e.y === 'D') { h.update('DELETED\n'); continue; }
    if (e.path.endsWith('/')) { h.update('DIR\n'); continue; } // -uall avoids this; never readFileSync a dir
    try {
      if (statSync(abs).isDirectory()) { h.update('DIR\n'); continue; }
      h.update(createHash('sha256').update(readFileSync(abs)).digest('hex') + '\n');
    } catch { h.update('UNREADABLE\n'); } // an odd/transient path can never crash the gate
  }
  return `dirty:${head}:${h.digest('hex')}`;
}

// ---------------------------------------------------------------- IO (atomic + schemaVersion + revision + shape)
let tmpSeq = 0;
const tmpPath = (file) => `${file}.tmp.${process.pid}.${++tmpSeq}`; // unique suffix → safe under concurrent writers
// Shape contract: required top-level fields per control file, so valid-JSON-but-missing-a-field fails
// closed at read time instead of silently rendering `undefined`.
const REQUIRED_FIELDS = {
  'tasks.json': ['milestone', 'nextPath', 'snapshot', 'tasks'],
  'gates.json': ['head', 'diffFingerprint', 'lint', 'test', 'build', 'typecheck'],
  'approvals.json': ['approvals'],
};
function readJson(file) {
  if (!existsSync(file)) throw new Error(`missing control file: ${rel(file)} (run: ai-control init)`);
  let data;
  try { data = JSON.parse(readFileSync(file, 'utf8')); }
  catch (e) { throw new Error(`invalid JSON in ${rel(file)}: ${e.message}`); }
  if (data.schemaVersion !== SCHEMA_VERSION) {
    throw new Error(`schemaVersion mismatch in ${rel(file)}: got ${data.schemaVersion}, want ${SCHEMA_VERSION}`);
  }
  const base = file.split(/[\\/]/).pop();
  for (const f of (REQUIRED_FIELDS[base] || [])) if (!(f in data)) throw new Error(`${rel(file)}: missing required field "${f}" (shape validation)`);
  if (base === 'tasks.json' && !Array.isArray(data.tasks)) throw new Error(`${rel(file)}: "tasks" must be an array`);
  if (base === 'approvals.json' && !Array.isArray(data.approvals)) throw new Error(`${rel(file)}: "approvals" must be an array`);
  return data;
}
// Optimistic concurrency: caller passes the revision it read; we re-check just before writing.
function writeJsonAtomic(file, data, expectedRevision) {
  if (existsSync(file) && expectedRevision != null) {
    const cur = JSON.parse(readFileSync(file, 'utf8'));
    if (cur.revision !== expectedRevision) {
      throw new Error(`revision conflict on ${rel(file)}: read ${expectedRevision}, on disk ${cur.revision} — re-read and retry`);
    }
  }
  data.schemaVersion = SCHEMA_VERSION;
  data.revision = (data.revision ?? 0) + 1;
  const tmp = tmpPath(file);
  writeFileSync(tmp, `${JSON.stringify(data, null, 2)}\n`, 'utf8');
  renameSync(tmp, file); // atomic on the same volume
}
function writeFileAtomic(file, content) {
  const tmp = tmpPath(file);
  writeFileSync(tmp, content, 'utf8');
  renameSync(tmp, file);
}
function appendEvent(type, task, payload) {
  const lines = existsSync(F.events)
    ? readFileSync(F.events, 'utf8').split('\n').filter((l) => l.trim())
    : [];
  let maxId = 0; // monotonic: max over ALL parseable ids (a corrupt last line can't reset the counter)
  for (const l of lines) { try { const id = JSON.parse(l).id; if (Number.isInteger(id) && id > maxId) maxId = id; } catch { /* skip corrupt line */ } }
  const ev = { id: maxId + 1, ts: new Date().toISOString(), task: task ?? null, type, head: gitHead(), payload: payload ?? {} };
  writeFileAtomic(F.events, `${lines.join('\n')}${lines.length ? '\n' : ''}${JSON.stringify(ev)}\n`); // atomic temp+rename
  return ev;
}
const rel = (p) => p.replace(REPO_ROOT, '').replace(/\\/g, '/').replace(/^\//, '');
const norm = (s) => s.replace(/\r\n/g, '\n');

// `--key value` / bare `--flag` parser; positional args land in `_`.
function parseFlags(args) {
  const out = { _: [] };
  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a.startsWith('--')) {
      const key = a.slice(2);
      const next = args[i + 1];
      if (next === undefined || next.startsWith('--')) out[key] = true;
      else { out[key] = next; i++; }
    } else out._.push(a);
  }
  return out;
}
const splitList = (v, sep = ',') => (typeof v === 'string' && v.length ? v.split(sep).map((s) => s.trim()).filter(Boolean) : []);
// Hash a repo-relative doc path. Null if missing/dir/unreadable. For requiredDocs.
function docHash(p) {
  const abs = join(REPO_ROOT, p);
  try { if (!existsSync(abs) || statSync(abs).isDirectory()) return null; return createHash('sha256').update(readFileSync(abs)).digest('hex'); }
  catch { return null; }
}
// Canonical repo-relative doc path so ".ai/x", "./.ai/x", ".ai\\x" all key/compare identically.
function canonDoc(p) { return relative(REPO_ROOT, resolve(REPO_ROOT, String(p).replace(/\\/g, '/'))).replace(/\\/g, '/'); }

// ---------------------------------------------------------------- renderers (PURE: control state only, no wall clock)
function bullets(arr, indent = '') { return (arr || []).map((x) => `${indent}- ${x}`).join('\n'); }

function renderCurrentState(t, gates) {
  const s = t.snapshot || {};
  const g = gates;
  const out = [
    GEN_HEADER,
    '',
    '# Current State',
    '',
    `## Snapshot (${s.asOf || ''})`.trimEnd(),
    `- Branch \`${s.branch || 'main'}\` · HEAD = \`${short(g.head)}\` (last gated commit) · run \`ai-control status\` for live tree + gate freshness.`,
    `- Gates @ this HEAD: lint ${g.lint} · **${g.test?.count} tests** ${g.test?.pass ? 'passing' : 'not-passing'} · build ${g.build} · typecheck ${g.typecheck}.`,
  ];
  if (s.tag) out.push(`- Tag ${s.tag}.`);
  out.push('', '## Active milestone', `- **${t.milestone}**`, bullets(s.milestoneDetail));
  const at = activeTask(t);
  if (at) out.push('', '## Active task', `- **${at.id}** ${at.title} — taskState \`${at.state}\` · delivery \`${at.delivery || 'uncommitted'}\` (mode ${at.mode || '?'}, model ${at.model || '?'})`);
  out.push('', '## Next step', `- **${t.nextPath}** Candidates:`, bullets(s.nextPathCandidates, '  '));
  out.push('', '## Top risks', bullets(s.risks));
  out.push('', '## Environment', bullets(s.env));
  if (s.pointers) out.push('', '## Pointers', `- ${s.pointers}`);
  out.push('');
  return `${out.join('\n')}`;
}

function activeTask(t) {
  return (t.tasks || []).find((x) => x.state === 'in_progress' || x.state === 'review') || null;
}

function renderCurrentFocus(t) {
  const s = t.snapshot || {};
  const at = activeTask(t);
  const out = [
    GEN_HEADER,
    '',
    '# Current Focus',
    '',
    '## Milestone',
    `- **${t.milestone}**`,
    bullets(s.milestoneDetail),
    '',
    '## Active slice',
  ];
  if (at) {
    out.push(`- **${at.id} — ${at.title}**`);
    out.push(`  - taskState \`${at.state}\` · delivery \`${at.delivery || 'uncommitted'}\` · mode ${at.mode || '?'} · model ${at.model || '?'}`);
    if (at.scope?.in?.length) out.push(`  - In scope: ${at.scope.in.join('; ')}`);
    if (at.scope?.out?.length) out.push(`  - Out of scope: ${at.scope.out.join('; ')}`);
    if (at.requiredDocs?.length) out.push(`  - Required docs (${(at.docsReviewed || []).length}/${at.requiredDocs.length} reviewed): ${at.requiredDocs.join(', ')}`);
    if (at.checkpoints?.length) out.push(`  - Checkpoints: ${at.checkpoints.length}`);
  } else {
    out.push(`- **NONE — awaiting the next direction.** ${t.nextPath} Candidates live in \`tasks.md\` / \`current-state.md\`.`);
  }
  out.push('', `_(${loadConfig().ownerFilesNote})_`, '');
  return out.join('\n');
}

function renderTasks(t) {
  const s = t.snapshot || {};
  const b = t.backlog || {};
  const active = (t.tasks || []).filter((x) => ['ready', 'in_progress', 'review'].includes(x.state));
  const out = [GEN_HEADER, '', '# Tasks', '', '## Active queue'];
  if (active.length) {
    for (const x of active) out.push(`- **${x.id}** [${x.state} · ${x.delivery || 'uncommitted'}] ${x.title}`);
  } else {
    out.push(`- **NONE in flight.** ${t.milestone}. The next slice is the user's pick from the candidates below.`);
  }
  out.push('', '## Next-path candidates (PM confirms one with the user)', bullets(s.nextPathCandidates));
  out.push('', '## Product backlog', bullets(b.product));
  out.push('', '## Technical backlog', bullets(b.technical));
  out.push('', '## Do Not Do Now', bullets(b.doNotDoNow));
  out.push('');
  return out.join('\n');
}

function renderAll() {
  const t = readJson(F.tasks);
  const gates = readJson(F.gates);
  return {
    [GEN.state]: renderCurrentState(t, gates),
    [GEN.focus]: renderCurrentFocus(t),
    [GEN.tasks]: renderTasks(t),
  };
}

// ---------------------------------------------------------------- worklog (freeze history, render events below)
function readEvents() {
  if (!existsSync(F.events)) return [];
  const evs = [];
  for (const l of readFileSync(F.events, 'utf8').split('\n')) { if (!l.trim()) continue; try { evs.push(JSON.parse(l)); } catch { /* skip corrupt */ } }
  return evs;
}
function summarizePayload(e) {
  const p = e.payload || {};
  switch (e.type) {
    case 'control.init': return p.note || 'control plane initialized';
    case 'task.create': return `created "${p.title || ''}"` + (p.mode ? ` · mode ${p.mode}` : '') + (p.model ? ` · model ${p.model}` : '');
    case 'task.ready': return 'ready for a coder';
    case 'task.start': return `started (headAtStart ${short(p.headAtStart)})`;
    case 'task.checkpoint': return `checkpoint${p.note ? `: ${p.note}` : ''}`;
    case 'task.finish': return `finished → review${p.commit ? ` (${short(p.commit)})` : ''}${p.summary ? `: ${p.summary}` : ''}`;
    case 'task.accept': return 'accepted (PM gate)';
    case 'task.reopen': return 'reopened (blocked → ready)';
    case 'task.block': return `blocked${p.reason ? `: ${p.reason}` : ''}`;
    case 'task.abandon': return `abandoned${p.reason ? `: ${p.reason}` : ''}`;
    case 'delivery': return `delivery → ${p.delivery}${p.commit ? ` (${short(p.commit)})` : ''}`;
    case 'gate.result': return `gate ${p.gate} = ${p.value}`;
    default: return JSON.stringify(p);
  }
}
// PURE function of events.jsonl (stored ts/head — no wall clock). Newest first.
function renderWorklogGenerated() {
  const evs = readEvents().sort((a, b) => (b.id || 0) - (a.id || 0));
  const out = [GEN_HEADER, '', '## Control event log (generated from .ai/control/events.jsonl — newest first)', ''];
  if (!evs.length) out.push('_(no control events yet)_');
  for (const e of evs) out.push(`- **${e.ts}** · \`${e.type}\` · task ${e.task ? `\`${e.task}\`` : '—'} · @${short(e.head)} — ${summarizePayload(e)}`);
  out.push('');
  // Defensive: never let event text re-introduce the freeze marker into generated output.
  return out.join('\n').split(WORKLOG_MARKER).join('<!-- (marker text neutralized) -->');
}
// Freeze everything above the marker (verbatim); regenerate only below. First run treats the whole existing
// file as frozen legacy and appends the marker + generated section.
function syncWorklog() {
  const existing = existsSync(WORKLOG) ? readFileSync(WORKLOG, 'utf8') : '';
  const idx = existing.indexOf(WORKLOG_MARKER);
  if (idx !== existing.lastIndexOf(WORKLOG_MARKER)) {
    throw new Error('worklog.md has MULTIPLE freeze markers — refusing to render (it would silently drop history between them). Remove the stray marker(s) manually, then sync.');
  }
  let legacy;
  if (idx >= 0) legacy = existing.slice(0, idx); // verbatim — never touched again
  else if (!existing.length) legacy = '# Worklog\n\n> History above the marker is frozen. New control events render below.\n\n';
  else legacy = existing.endsWith('\n\n') ? existing : existing.endsWith('\n') ? `${existing}\n` : `${existing}\n\n`;
  const content = `${legacy}${WORKLOG_MARKER}\n\n${renderWorklogGenerated()}`;
  const before = existsSync(WORKLOG) ? norm(readFileSync(WORKLOG, 'utf8')) : null;
  if (before !== norm(content)) { writeFileAtomic(WORKLOG, content); return 'updated'; }
  return 'unchanged';
}

// ---------------------------------------------------------------- commands
function ensureControlDir() { if (!existsSync(CONTROL_DIR)) mkdirSync(CONTROL_DIR, { recursive: true }); }

function cmdSync() {
  const rendered = renderAll();
  const written = [];
  for (const [file, content] of Object.entries(rendered)) {
    const before = existsSync(file) ? norm(readFileSync(file, 'utf8')) : null;
    if (before !== norm(content)) { writeFileAtomic(file, content); written.push(`${rel(file)} (updated)`); }
    else written.push(`${rel(file)} (unchanged)`);
  }
  const wl = syncWorklog();
  written.push(`${rel(WORKLOG)} — below freeze marker (${wl}); history above the marker is frozen`);
  console.log('sync — generated views:');
  written.forEach((w) => console.log(`  ${w}`));
  console.log('(content ABOVE the worklog marker + authored files are never touched.)');
  return 0;
}

function gateFreshness(gates) {
  const headNow = gitHead();
  const fpNow = computeFingerprint();
  const headOk = gates.head === headNow;
  const fpOk = gates.diffFingerprint === fpNow;
  return { headOk, fpOk, fresh: headOk && fpOk, headNow, fpNow };
}

function cmdStatus() {
  const t = readJson(F.tasks);
  const gates = readJson(F.gates);
  const approvals = readJson(F.approvals);
  const cfg = loadConfig();
  const fr = gateFreshness(gates);
  const counts = {};
  for (const x of t.tasks || []) counts[x.state] = (counts[x.state] || 0) + 1;
  const at = activeTask(t);
  const pendingApprovals = (approvals.approvals || []).filter((a) => !a.used);

  console.log('== ai-control status ==');
  console.log(`project   : ${cfg.projectName}`);
  console.log(`milestone : ${t.milestone}`);
  console.log(`next path : ${t.nextPath}`);
  const treeLabel = fr.fpNow.startsWith('clean:') ? 'CLEAN' : fr.fpNow.startsWith('error:') ? `UNAVAILABLE (${fr.fpNow})` : 'DIRTY';
  console.log(`git       : ${gitBranch() || '(no branch)'} @ ${gitHeadShort() || '(no HEAD)'} · tree ${treeLabel}`);
  console.log(`gates     : @${short(gates.head)} lint=${gates.lint} test=${gates.test?.count}${gates.test?.pass ? '' : '(not-pass)'} build=${gates.build} typecheck=${gates.typecheck} -> ${fr.fresh ? 'FRESH' : 'STALE (HEAD/diff moved since gates ran)'}`);
  if (!t.tasks?.length) {
    console.log('tasks     : none (create one: ai-control task create --id <ID> --title "...")');
  } else {
    console.log(`tasks     : ${t.tasks.length} total — ${Object.entries(counts).map(([k, v]) => `${k}:${v}`).join(' ')}`);
    if (at) {
      console.log(`  active  : ${at.id} — ${at.title}`);
      console.log(`            taskState=${at.state} · deliveryState=${at.delivery || 'uncommitted'} · approvals=${pendingApprovals.filter((a) => a.task === at.id).length} pending`);
    }
  }
  console.log(`approvals : ${pendingApprovals.length} pending, ${(approvals.approvals || []).length} total`);
  return 0;
}

function cmdCheck() {
  const findings = [];
  let t, gates, approvals;
  try { t = readJson(F.tasks); } catch (e) { findings.push(`tasks.json: ${e.message}`); }
  try { gates = readJson(F.gates); } catch (e) { findings.push(`gates.json: ${e.message}`); }
  try { approvals = readJson(F.approvals); } catch (e) { findings.push(`approvals.json: ${e.message}`); }
  if (!existsSync(F.events)) findings.push('events.jsonl: missing');
  else {
    const evLines = readFileSync(F.events, 'utf8').split('\n').filter((l) => l.trim());
    const ids = new Set();
    let bad = false; let dup = false;
    for (const l of evLines) { let o; try { o = JSON.parse(l); } catch { bad = true; continue; } if (ids.has(o.id)) dup = true; else ids.add(o.id); }
    if (bad) findings.push('events.jsonl: contains a non-JSON line');
    if (dup) findings.push('events.jsonl: duplicate event id(s) — monotonic-id invariant broken');
  }

  if (gates) {
    const fr = gateFreshness(gates);
    if (!fr.headOk) findings.push(`gates.json STALE: recorded head ${short(gates.head)} != current HEAD ${short(fr.headNow)}`);
    if (!fr.fpOk) findings.push(`gates.json STALE: diffFingerprint != current code fingerprint (code changed since gates ran)`);
  }

  if (t && gates) {
    let rendered;
    try { rendered = renderAll(); } catch (e) { findings.push(`render failed: ${e.message}`); rendered = null; }
    if (rendered) {
      for (const [file, content] of Object.entries(rendered)) {
        if (!existsSync(file)) findings.push(`${rel(file)}: not generated yet (run sync)`);
        else if (norm(readFileSync(file, 'utf8')) !== norm(content)) findings.push(`${rel(file)}: DRIFT — on-disk content != render of control state (was it hand-edited?)`);
      }
    }
  }

  for (const x of (t?.tasks || [])) {
    if (!x.id || typeof x.id !== 'string') findings.push(`a task is missing a string "id" (title: ${x.title || '?'})`);
    if (!TASK_STATES.includes(x.state)) findings.push(`task ${x.id}: invalid state "${x.state}"`);
    if (x.delivery && !DELIVERY_STATES.includes(x.delivery)) findings.push(`task ${x.id}: invalid delivery "${x.delivery}"`);
    if (x.delivery && x.delivery !== 'uncommitted' && !['in_progress', 'review', 'accepted'].includes(x.state)) findings.push(`task ${x.id}: deliveryState "${x.delivery}" on a "${x.state}" task (contradictory 3-axis state)`);
  }

  for (const a of (approvals?.approvals || [])) {
    if (a.task && !(t?.tasks || []).some((x) => x.id === a.task)) findings.push(`approval ${a.id}: references unknown task ${a.task}`);
  }

  // requiredDocs: for an ACTIVE task, verify the docsChanged DECLARATION by hash (machine checks the
  // declaration; the PM checks semantics).
  for (const x of (t?.tasks || [])) {
    if (x.state !== 'in_progress' && x.state !== 'review') continue;
    const base = x.docBaselines || {};
    for (const p of (x.requiredDocs || [])) {
      const cur = docHash(p);
      if (cur == null) { findings.push(`task ${x.id}: requiredDoc ${p} missing on disk`); continue; }
      const changed = (base[p] ?? null) !== cur; // null baseline (doc created during the task) counts as changed
      const declared = (x.docsChanged || []).includes(p);
      if (changed && !declared) findings.push(`task ${x.id}: requiredDoc ${p} CHANGED/created since start but not declared in docsChanged`);
      if (declared && !changed) findings.push(`task ${x.id}: ${p} declared in docsChanged but its hash is unchanged since start`);
    }
    if (x.state === 'review') {
      const notReviewed = (x.requiredDocs || []).filter((p) => !(x.docsReviewed || []).includes(p));
      if (notReviewed.length) findings.push(`task ${x.id}: requiredDoc(s) not declared reviewed before finish: ${notReviewed.join(', ')}`);
    }
  }

  // worklog: the section BELOW the marker must match the event render; history ABOVE is frozen (never checked).
  if (existsSync(WORKLOG)) {
    const w = readFileSync(WORKLOG, 'utf8');
    const wi = w.indexOf(WORKLOG_MARKER);
    if (wi < 0) findings.push('worklog.md: missing the ai-control freeze marker (run sync to freeze history + render events)');
    else if (wi !== w.lastIndexOf(WORKLOG_MARKER)) findings.push('worklog.md: MULTIPLE freeze markers — do NOT run sync (it would drop history between them); remove the stray marker(s) manually');
    else {
      const below = norm(w.slice(wi + WORKLOG_MARKER.length)).replace(/^\n+/, '').trimEnd();
      const expected = norm(renderWorklogGenerated()).trimEnd();
      if (below !== expected) findings.push('worklog.md: DRIFT below the freeze marker (hand-edited below the line? run sync)');
    }
  }

  if (findings.length === 0) { console.log('ai-control check: OK — control state consistent, gates fresh, generated views in sync.'); return 0; }
  console.error('ai-control check: FAIL');
  findings.forEach((f) => console.error(`  - ${f}`));
  return 1;
}

function cmdDoctor() {
  console.log('== ai-control doctor (read-only health) ==');
  const ok = (b) => (b ? 'OK ' : 'XX ');
  const tl = git(['rev-parse', '--show-toplevel']).replace(/\\/g, '/');
  const rootOk = tl === REPO_ROOT.replace(/\\/g, '/');
  console.log(`${ok(rootOk)} repo root resolved (${rel(REPO_ROOT) || '.'} == git toplevel)`);
  console.log(`${ok(existsSync(F.config))} .ai/control/config.json present (${existsSync(F.config) ? loadConfig().projectName : 'run: ai-control init'})`);
  let t, gates, approvals;
  for (const [k, file] of Object.entries(F)) {
    if (k === 'config') continue;
    if (k === 'events') { console.log(`${ok(existsSync(file))} ${rel(file)} present`); continue; }
    try { const d = readJson(file); console.log(`${ok(true)} ${rel(file)} valid (schemaVersion ${d.schemaVersion}, revision ${d.revision})`); if (k === 'tasks') t = d; if (k === 'gates') gates = d; if (k === 'approvals') approvals = d; }
    catch (e) { console.log(`${ok(false)} ${rel(file)} — ${e.message}`); }
  }
  if (gates) { const fr = gateFreshness(gates); console.log(`${ok(fr.fresh)} gates fresh vs HEAD+diff (${fr.fresh ? 'fresh' : 'STALE'})`); }
  if (t && gates) {
    try {
      const rendered = renderAll();
      let synced = true;
      for (const [file, content] of Object.entries(rendered)) if (!existsSync(file) || norm(readFileSync(file, 'utf8')) !== norm(content)) synced = false;
      console.log(`${ok(synced)} generated views in sync with control state${synced ? '' : ' (run sync)'}`);
    } catch (e) { console.log(`${ok(false)} render — ${e.message}`); }
  }
  const pending = (approvals?.approvals || []).filter((a) => !a.used);
  console.log(`${ok(true)} approvals: ${pending.length} pending / ${(approvals?.approvals || []).length} total`);
  console.log('doctor: read-only; see `check` for the gate verdict (exit code).');
  return 0;
}

// internal: exercise the atomic-write/revision path + bind gates to the current change-set.
function cmdGateSet(name, passStr) {
  const gates = readJson(F.gates);
  const rev = gates.revision;
  if (name === 'test') {
    const count = Number.parseInt(passStr, 10);
    if (!Number.isFinite(count) || count < 0) throw new Error('usage: gate set test <count>');
    gates.test = { pass: true, count };
  } else {
    const valid = ['lint', 'build', 'typecheck'];
    if (!valid.includes(name)) throw new Error(`unknown gate "${name}" (expected ${valid.join('|')}|test)`);
    gates[name] = passStr === 'pass' || passStr === 'true' ? 'pass' : 'fail';
  }
  gates.head = gitHead();
  gates.diffFingerprint = computeFingerprint();
  gates.recordedAt = new Date().toISOString();
  writeJsonAtomic(F.gates, gates, rev);
  appendEvent('gate.result', null, { gate: name, value: name === 'test' ? gates.test : gates[name] });
  const valueLabel = name === 'test' ? `${gates.test.count} pass` : gates[name];
  console.log(`gate ${name} = ${valueLabel} (rebound to HEAD ${gitHeadShort()}; gates.json revision ${rev} -> ${rev + 1})`);
  return 0;
}

// ---------------------------------------------------------------- init (scaffold the control plane)
function seedTasks(cfg) {
  return {
    milestone: 'Project initialized — set your first milestone',
    nextPath: 'Fill .ai/PROJECT.md, then create the first task (ai-control task create).',
    snapshot: {
      asOf: '', branch: cfg.defaultBranch, milestoneDetail: ['Fill .ai/PROJECT.md with stack, branch, boundaries, and rules.'],
      nextPathCandidates: ['Create the first task: ai-control task create --id T-001 --title "..."'],
      risks: [], env: [], pointers: 'See .ai/PROJECT.md for the project brief.', tag: '',
    },
    backlog: { product: [], technical: [], doNotDoNow: [] },
    tasks: [],
  };
}
function projectMdSkeleton(cfg) {
  return [
    `# ${cfg.projectName} — Project Brief`,
    '',
    '> The ONE authored file you fill per project. The PM/coder skills read this for project specifics.',
    '> The four hot views (current-state / current-focus / tasks / worklog) are GENERATED — never hand-edit.',
    '',
    '## Stack',
    `- Language / framework: <fill in>`,
    `- Default branch: \`${cfg.defaultBranch}\``,
    `- Code lives in: ${cfg.codePaths.map((p) => `\`${p}/\``).join(', ')}`,
    `- Database / migrations: ${cfg.hasDb ? 'yes' : 'no'}${cfg.hasDb ? ' — migrations are written, PM-reviewed, then applied' : ''}`,
    `- Deploy surface: ${cfg.hasDeploy ? 'yes' : 'no'}`,
    '',
    '## Architecture boundaries (what the coder must respect)',
    '- <e.g. UI → hooks → services → data; no direct data access from components>',
    '- <e.g. generated types are truth; mappers are pure; services own queries/mutations>',
    '',
    '## Security / privacy rules',
    '- <e.g. authz is the real boundary; never expose secrets in the frontend>',
    `${cfg.hasDb ? '- <DB: row-level rules, the safe-column pattern for mixed-sensitivity tables, etc.>' : ''}`,
    '',
    '## Verification policy',
    '- Gates: lint / test / build / typecheck must pass before finish.',
    '- Adversarial reviewers (security / architecture / fidelity) on M/L slices; small slices may self-review.',
    '',
    '## Mode + model defaults',
    '- ultracode (build+verify) for risky slices; max (solo) for simple UI/refactor/copy.',
    '- Coder model: cheaper to save on low-risk; top model for hard/security-sensitive slices.',
    '',
  ].join('\n');
}
// --- web preset (M1: `init --web`) ---------------------------------------------------------------
// Shallow, single-pass stack detect for an EXISTING repo. Deterministic (fs only, no wall clock).
// Deliberately shallow — the deep multi-round /onboard analysis is M2. Never throws: unreadable inputs
// degrade to "not detected".
function detectWebStack() {
  const facts = { framework: null, ssr: null, typescript: false, tailwind: false, shadcn: false, backend: null, configs: [], codePaths: [] };
  const pkgPath = join(REPO_ROOT, 'package.json');
  if (existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
      const deps = { ...(pkg.dependencies || {}), ...(pkg.devDependencies || {}) };
      if (deps.next) { facts.framework = 'Next.js'; facts.ssr = true; }
      else if (deps.vite) { facts.framework = 'Vite'; facts.ssr = false; }
      else if (deps['react-scripts']) { facts.framework = 'CRA'; facts.ssr = false; }
      if (deps.typescript) facts.typescript = true;
      if (deps.tailwindcss) facts.tailwind = true;
      if (deps['@supabase/supabase-js']) facts.backend = 'Supabase';
      else if (deps['drizzle-orm']) facts.backend = 'Drizzle';
    } catch { /* unreadable/invalid package.json → fall through to file-based checks */ }
  }
  if (!facts.typescript && existsSync(join(REPO_ROOT, 'tsconfig.json'))) facts.typescript = true;
  if (existsSync(join(REPO_ROOT, 'components.json'))) facts.shadcn = true;
  if (!facts.backend && existsSync(join(REPO_ROOT, 'supabase'))) facts.backend = 'Supabase';
  for (const f of ['next.config.js', 'next.config.mjs', 'next.config.ts', 'vite.config.js', 'vite.config.ts', 'tailwind.config.js', 'tailwind.config.ts', 'tsconfig.json', 'drizzle.config.ts', 'components.json']) {
    if (existsSync(join(REPO_ROOT, f))) facts.configs.push(f);
  }
  for (const d of ['src', 'app', 'components', 'lib', 'pages']) {
    if (existsSync(join(REPO_ROOT, d))) facts.codePaths.push(d);
  }
  if (!facts.codePaths.length) facts.codePaths = ['src'];
  return facts;
}
// A FILLED (not blank) web project brief: the locked P0 defaults + detected facts, pointing at web/*.md.
function projectMdWebSkeleton(cfg) {
  const d = cfg.detected;
  const stackLine = cfg.stack === 'vite'
    ? 'Vite + React + TypeScript (SPA — the no-SSR exception)'
    : 'Next.js (App Router) + TypeScript (SSR — the serious-app default)';
  const backendLine = cfg.backend === 'drizzle'
    ? 'Postgres + Drizzle + Next server actions (full control / no vendor lock-in — you own auth + authz)'
    : 'Supabase (Postgres + Auth + RLS) — authz lives in the DB, PROVABLE via the 2-identity isolation proof';
  const lines = [
    `# ${cfg.projectName} — Project Brief (web preset)`,
    '',
    '> The ONE authored file you fill per project. The PM/coder skills read this for project specifics.',
    '> The four hot views (current-state / current-focus / tasks / worklog) are GENERATED — never hand-edit.',
    `> Preset: **web** · mode: **${cfg.projectMode}**. Doctrine: \`web/STACK.md\`, \`web/FRONTEND.md\`, \`web/SECURITY.md\`, \`DECISIONS.md\`.`,
    '',
    '## Stack (locked P0 defaults — see DECISIONS.md)',
    `- Framework: ${stackLine}`,
    "- UI: Tailwind CSS + shadcn/ui — INVOKE shadcn (registry/MCP); compose, don't hand-roll (web/FRONTEND.md).",
    `- Backend: ${backendLine}`,
    `- Deploy target: ${cfg.deployTarget}`,
    `- Default branch: \`${cfg.defaultBranch}\``,
    `- Code lives in: ${cfg.codePaths.map((p) => `\`${p}/\``).join(', ')}`,
    '',
  ];
  if (d) {
    lines.push(
      '## Detected stack (auto — SHALLOW one-pass; verify, then run the deep /onboard analysis for M2)',
      `- Framework: ${d.framework || 'not detected'}${d.ssr === false ? ' (SPA)' : d.ssr ? ' (SSR)' : ''}`,
      `- TypeScript: ${d.typescript ? 'yes' : 'no'} · Tailwind: ${d.tailwind ? 'yes' : 'no'} · shadcn: ${d.shadcn ? 'yes' : 'no'}`,
      `- Backend: ${d.backend || 'not detected'}`,
      `- Config files: ${d.configs.length ? d.configs.join(', ') : 'none found'}`,
      '',
    );
  }
  lines.push(
    '## Architecture boundaries (what the coder must respect)',
    '- Data access from server components / server actions only; NO data fetching in client components.',
    '- Forms: server actions + SERVER-SIDE validation (client validation is UX only).',
    '- Types: generated DB types → domain types → pure mappers → services → UI.',
    '',
    '## Security / privacy rules (see web/SECURITY.md)',
    `- Profile: ${cfg.ssr ? 'SERVER/SSR (full surface: auth/session, CSRF, IDOR, SSRF, server-action authz)' : 'STATIC-SPA (XSS, bundle secrets, deps, CSP/headers, sanitization)'}.`,
    '- No secrets in the client bundle (`NEXT_PUBLIC_*` / `VITE_*` are PUBLIC by definition).',
    cfg.backend === 'supabase'
      ? '- Authz = RLS. Every data slice needs the EXECUTED 2-identity isolation proof (own=N / other=0) before "secure".'
      : '- You own authz — every data slice needs an EXECUTED access-control proof (own=N / other=0) before "secure".',
    '',
    '## Verification policy',
    '- Working-site gate: lint / test / build / typecheck pass + dev server boots + pages render (0 console errors).',
    '- Security gate (web): secrets scan over the BUILT bundle + dependency audit + the executed authz proof on data/auth/form slices.',
    '- Adversarial reviewers: fidelity/parity always on UI; security-web on forms/auth/data slices.',
    '',
    '## Mode + model defaults',
    '- ultracode (build+verify) for data/auth/security slices; max (solo) for simple UI/copy.',
    '- Coder model: cheaper for low-risk UI; top model for auth/security/data slices.',
    '',
  );
  return lines.join('\n');
}
function seedTasksWeb(cfg) {
  const isExisting = cfg.projectMode === 'existing';
  const scaffoldCmd = cfg.stack === 'vite' ? 'npm create vite@latest' : 'npx create-next-app@latest';
  const stackShort = cfg.stack === 'vite' ? 'Vite+React+TS' : 'Next.js (App Router)+TS';
  return {
    milestone: `Web project initialized (${cfg.projectMode}) — ${isExisting ? 'analyze, then build slice by slice' : 'scaffold, then build slice by slice'}`,
    nextPath: isExisting
      ? 'Verify the detected stack in .ai/PROJECT.md, run the deep /onboard analysis (M2), then create the first task.'
      : 'Scaffold the app (create the framework project), fill .ai/PROJECT.md, then create the first UI/data task.',
    snapshot: {
      asOf: '', branch: cfg.defaultBranch,
      milestoneDetail: [
        `Stack: ${stackShort} + Tailwind + shadcn · backend ${cfg.backend} · deploy ${cfg.deployTarget}.`,
        'Doctrine: web/STACK.md, web/FRONTEND.md, web/SECURITY.md, DECISIONS.md.',
      ],
      nextPathCandidates: isExisting
        ? ['Run the deep /onboard stack analysis (M2) to enrich PROJECT.md + seed a backlog.',
          'Create the first task: ai-control task create --id T-001 --title "..."']
        : [`Scaffold ${stackShort} + Tailwind + shadcn${cfg.backend === 'supabase' ? ' + Supabase' : ' + Drizzle'} (\`${scaffoldCmd}\`).`,
          'Create the first task: ai-control task create --id T-001 --title "..."'],
      risks: [], env: [],
      pointers: 'See .ai/PROJECT.md for the project brief; web/*.md for stack/frontend/security doctrine.', tag: '',
    },
    backlog: {
      product: [],
      technical: isExisting ? ['Deep /onboard analysis (M2) pending — the PROJECT.md auto-detect is a shallow one-pass.'] : [],
      doNotDoNow: [
        'Do not fetch data from client components (server components / server actions only).',
        'Do not put secrets in `NEXT_PUBLIC_*` / `VITE_*` (they ship to the browser).',
        cfg.backend === 'supabase'
          ? 'Do not ship a data slice without the executed 2-identity RLS isolation proof.'
          : 'Do not ship a data slice without an executed access-control proof.',
      ],
    },
    tasks: [],
  };
}
// Idempotent hook wiring for the web preset: copy the template to settings.json ONLY if absent (never
// clobber an existing settings.json). For the default Supabase stack, also gate the migration/edge-deploy
// tools. Returns a status string for the console.
function wireHooksFromTemplate(cfg) {
  const dst = join(REPO_ROOT, '.claude', 'settings.json');
  const tpl = join(REPO_ROOT, '.claude', 'settings.template.json');
  if (existsSync(dst)) return 'exists';
  if (!existsSync(tpl)) return 'no-template';
  let obj;
  try { obj = JSON.parse(readFileSync(tpl, 'utf8')); } catch { return 'bad-template'; }
  delete obj._comment;
  if (cfg.backend === 'supabase' && cfg.hasDb) {
    obj.hooks = obj.hooks || {};
    obj.hooks.PreToolUse = obj.hooks.PreToolUse || [];
    obj.hooks.PreToolUse.push({
      matcher: 'mcp__supabase__apply_migration',
      hooks: [{ type: 'command', command: 'node "${CLAUDE_PROJECT_DIR}/.claude/hooks/gate-migration.mjs"' }],
    });
    if (cfg.hasDeploy) {
      obj.hooks.PreToolUse.push({
        matcher: 'mcp__supabase__deploy_edge_function',
        hooks: [{ type: 'command', command: 'node "${CLAUDE_PROJECT_DIR}/.claude/hooks/gate-deploy-push.mjs"' }],
      });
    }
  }
  writeFileAtomic(dst, `${JSON.stringify(obj, null, 2)}\n`);
  return 'wired';
}
function cmdInit(rest) {
  const flags = parseFlags(rest);
  const web = !!flags.web;
  const hasPkg = existsSync(join(REPO_ROOT, 'package.json'));
  // new vs existing: an explicit flag wins; else for --web auto-detect from a package.json at the root.
  const projectMode = flags.existing ? 'existing' : flags.new ? 'new' : (web && hasPkg ? 'existing' : 'new');
  const stack = flags.spa ? 'vite' : 'next';
  const backend = flags.drizzle ? 'drizzle' : 'supabase';
  // coerce to a string: a bare `--deploy-target` (no value) parses as boolean `true` — treat that as "unset".
  const deployTargetFlag = typeof flags['deploy-target'] === 'string' ? flags['deploy-target'] : null;
  const detected = web && projectMode === 'existing' ? detectWebStack() : null;
  const codePaths = splitList(flags.code).length
    ? splitList(flags.code)
    : web
      ? (detected && detected.codePaths.length ? detected.codePaths : (stack === 'vite' ? ['src'] : ['src', 'app', 'components', 'lib']))
      : ['src'];

  const cfg = {
    schemaVersion: SCHEMA_VERSION,
    projectName: flags.name || (web ? 'My Web App' : 'My Project'),
    defaultBranch: flags.branch || 'main',
    codePaths,
    hasDb: web ? !flags['no-db'] : !!flags.db,
    hasDeploy: web ? (deployTargetFlag !== 'none') : !!flags.deploy,
    ownerFilesNote: 'current truth → current-state.md · queue → tasks.md · active slice → current-focus.md · history → worklog.md',
  };
  if (web) {
    cfg.preset = 'web';
    cfg.projectMode = projectMode;
    cfg.stack = stack;
    cfg.ssr = !flags.spa;
    cfg.backend = backend;
    cfg.deployTarget = deployTargetFlag || (cfg.hasDeploy ? 'vercel' : 'none');
    if (detected) cfg.detected = detected;
  }

  ensureControlDir();
  writeFileAtomic(F.config, `${JSON.stringify(cfg, null, 2)}\n`);
  if (!existsSync(F.tasks)) writeJsonAtomic(F.tasks, web ? seedTasksWeb(cfg) : seedTasks(cfg), null);
  if (!existsSync(F.gates)) writeJsonAtomic(F.gates, { head: '', diffFingerprint: '', lint: 'unknown', test: { pass: false, count: 0 }, build: 'unknown', typecheck: 'unknown' }, null);
  if (!existsSync(F.approvals)) writeJsonAtomic(F.approvals, { approvals: [] }, null);
  if (!existsSync(F.events)) writeFileAtomic(F.events, '');
  // bind gates to the current change-set so the first `check` is fresh
  const gates = readJson(F.gates); const rev = gates.revision;
  gates.head = gitHead(); gates.diffFingerprint = computeFingerprint(); gates.recordedAt = new Date().toISOString();
  writeJsonAtomic(F.gates, gates, rev);
  appendEvent('control.init', null, { note: `initialized "${cfg.projectName}"${web ? ` [web:${stack}/${backend}/${projectMode}]` : ''} (branch ${cfg.defaultBranch}, code ${cfg.codePaths.join('+')}, db ${cfg.hasDb}, deploy ${cfg.hasDeploy})` });
  if (!existsSync(PROJECT_MD)) writeFileAtomic(PROJECT_MD, web ? projectMdWebSkeleton(cfg) : projectMdSkeleton(cfg));
  const wired = web ? wireHooksFromTemplate(cfg) : 'skipped';
  cmdSync();
  console.log('');
  console.log(`init OK — control plane scaffolded for "${cfg.projectName}"${web ? ` (web preset · ${stack}/${backend} · ${projectMode})` : ''}.`);
  if (web) {
    console.log(
      wired === 'wired' ? 'Hooks wired: .claude/settings.template.json → .claude/settings.json (warning mode).'
        : wired === 'exists' ? 'Hooks: .claude/settings.json already present — left as-is (merge the template\'s "hooks" block if needed).'
          : wired === 'bad-template' ? 'Hooks NOT wired: .claude/settings.template.json is invalid JSON — fix it, then copy it to .claude/settings.json.'
            : wired === 'no-template' ? 'Hooks NOT wired: .claude/settings.template.json is missing — restore it, then copy to .claude/settings.json.'
              : 'Hooks: copy .claude/settings.template.json → .claude/settings.json (or merge its "hooks" block).');
    if (projectMode === 'new') {
      console.log(`Next: scaffold the app (${stack === 'vite' ? 'npm create vite@latest' : 'npx create-next-app@latest'}), fill .ai/PROJECT.md, then /pm to create the first task.`);
    } else {
      console.log('Next: verify the auto-detected stack in .ai/PROJECT.md, run the deep /onboard analysis (M2), then /pm to create the first task.');
    }
  } else {
    console.log('Next: fill .ai/PROJECT.md, then use /pm (PM chat) to create the first task; /task <ID> in a coder chat.');
    console.log('Wire the hooks by copying .claude/settings.template.json → .claude/settings.json (or merge its "hooks" block).');
  }
  return 0;
}

// ---------------------------------------------------------------- task lifecycle (3-axis, events.jsonl)
function findTask(t, id) { const x = (t.tasks || []).find((k) => k.id === id); if (!x) throw new Error(`unknown task: ${id || '(none given)'}`); return x; }
function requireState(x, ...states) { if (!states.includes(x.state)) throw new Error(`task ${x.id} is "${x.state}"; this transition needs ${states.join('|')}`); }
const nowIso = () => new Date().toISOString();

function cmdTask(rest) {
  const sub = rest[0];
  const flags = parseFlags(rest.slice(1));
  const t = readJson(F.tasks);
  const rev = t.revision;
  const id = flags.id || flags._[0];
  const save = () => writeJsonAtomic(F.tasks, t, rev);

  switch (sub) {
    case 'create': {
      if (!flags.id || !flags.title) throw new Error('task create --id <ID> --title <T> [--owner coder|PM] [--mode max|ultracode] [--model ...] [--in "a;b"] [--out "a;b"] [--gates "a;b"] [--docs "a,b"]');
      t.tasks = t.tasks || [];
      if (t.tasks.some((k) => k.id === flags.id)) throw new Error(`task ${flags.id} already exists`);
      const task = {
        id: flags.id, title: flags.title, state: 'backlog',
        owner: flags.owner || 'coder', mode: flags.mode || null, model: flags.model || null,
        scope: { in: splitList(flags.in, ';'), out: splitList(flags.out, ';'), gates: splitList(flags.gates, ';') },
        requiredDocs: splitList(flags.docs).map(canonDoc), docBaselines: {}, docsReviewed: [], docsChanged: [],
        createdBy: 'PM', createdAt: nowIso(), updatedAt: nowIso(),
        headAtStart: null, checkpoints: [], delivery: 'uncommitted',
        result: { commit: null, pushed: false, summary: null },
      };
      t.tasks.push(task); save();
      appendEvent('task.create', task.id, { title: task.title, mode: task.mode, model: task.model, requiredDocs: task.requiredDocs });
      console.log(`created ${task.id} [backlog] (owner ${task.owner}${task.requiredDocs.length ? `, ${task.requiredDocs.length} requiredDocs` : ''})`);
      return 0;
    }
    case 'ready': { const x = findTask(t, id); requireState(x, 'backlog'); x.state = 'ready'; x.updatedAt = nowIso(); save(); appendEvent('task.ready', x.id, {}); console.log(`${x.id} → ready`); return 0; }
    case 'start': {
      const x = findTask(t, id); requireState(x, 'ready');
      const busy = (t.tasks || []).find((k) => k.id !== x.id && k.state === 'in_progress');
      if (busy) throw new Error(`another task is already in_progress: ${busy.id} — finish/block/abandon it before starting ${x.id} (one active task at a time)`);
      x.state = 'in_progress'; x.headAtStart = gitHead(); x.updatedAt = nowIso();
      x.docBaselines = {}; for (const p of x.requiredDocs) x.docBaselines[p] = docHash(p);
      save(); appendEvent('task.start', x.id, { headAtStart: x.headAtStart, requiredDocs: x.requiredDocs });
      console.log(`${x.id} → in_progress (headAtStart ${short(x.headAtStart)}; ${x.requiredDocs.length} requiredDoc baseline(s) captured)`);
      return 0;
    }
    case 'checkpoint': {
      const x = findTask(t, id); requireState(x, 'in_progress');
      const cp = { at: nowIso(), head: gitHead(), diffFingerprint: computeFingerprint(), note: flags.note || '', docsReviewed: splitList(flags['docs-reviewed']).map(canonDoc), docsChanged: splitList(flags['docs-changed']).map(canonDoc) };
      x.checkpoints.push(cp);
      x.docsReviewed = Array.from(new Set([...x.docsReviewed, ...cp.docsReviewed]));
      x.docsChanged = Array.from(new Set([...x.docsChanged, ...cp.docsChanged]));
      x.updatedAt = nowIso(); save();
      appendEvent('task.checkpoint', x.id, { note: cp.note, fingerprint: cp.diffFingerprint, docsReviewed: cp.docsReviewed, docsChanged: cp.docsChanged });
      console.log(`${x.id} checkpoint #${x.checkpoints.length}${cp.note ? `: ${cp.note}` : ''}`);
      return 0;
    }
    case 'finish': {
      const x = findTask(t, id); requireState(x, 'in_progress');
      x.state = 'review';
      if (flags.commit) x.result.commit = flags.commit;
      if (flags.summary) x.result.summary = flags.summary;
      x.docsReviewed = Array.from(new Set([...x.docsReviewed, ...splitList(flags['docs-reviewed']).map(canonDoc)]));
      x.docsChanged = Array.from(new Set([...x.docsChanged, ...splitList(flags['docs-changed']).map(canonDoc)]));
      x.updatedAt = nowIso(); save();
      appendEvent('task.finish', x.id, { commit: x.result.commit, summary: x.result.summary });
      console.log(`${x.id} → review (PM gate next: task accept ${x.id})`);
      return 0;
    }
    case 'accept': { const x = findTask(t, id); requireState(x, 'review'); x.state = 'accepted'; x.updatedAt = nowIso(); save(); appendEvent('task.accept', x.id, {}); console.log(`${x.id} → accepted (PM gate)`); return 0; }
    case 'reopen': { const x = findTask(t, id); requireState(x, 'blocked'); x.state = 'ready'; x.updatedAt = nowIso(); save(); appendEvent('task.reopen', x.id, {}); console.log(`${x.id} → ready (reopened from blocked)`); return 0; }
    case 'block': { const x = findTask(t, id); x.state = 'blocked'; x.updatedAt = nowIso(); save(); appendEvent('task.block', x.id, { reason: flags.reason || '' }); console.log(`${x.id} → blocked`); return 0; }
    case 'abandon': { const x = findTask(t, id); x.state = 'abandoned'; x.updatedAt = nowIso(); save(); appendEvent('task.abandon', x.id, { reason: flags.reason || '' }); console.log(`${x.id} → abandoned`); return 0; }
    case 'deliver': {
      const x = findTask(t, id); requireState(x, 'in_progress', 'review', 'accepted');
      const ds = flags.to || (flags.id ? flags._[0] : flags._[1]); // works for both `deliver <id> <state>` and `--id <id> <state>`
      if (!DELIVERY_STATES.includes(ds) || ds === 'uncommitted') throw new Error(`task deliver <id> <committed|pushed|deployed> [--commit <sha>]`);
      x.delivery = ds; if (flags.commit) x.result.commit = flags.commit; if (ds === 'pushed' || ds === 'deployed') x.result.pushed = true;
      x.updatedAt = nowIso(); save(); appendEvent('delivery', x.id, { delivery: ds, commit: x.result.commit });
      console.log(`${x.id} delivery → ${ds}`);
      return 0;
    }
    default: throw new Error('task <create|ready|start|checkpoint|finish|accept|block|reopen|abandon|deliver> …');
  }
}

// ---------------------------------------------------------------- dispatch
function main() {
  ensureControlDir();
  const [cmd, ...rest] = process.argv.slice(2);
  try {
    switch (cmd) {
      case 'init': return cmdInit(rest);
      case 'status': return cmdStatus();
      case 'sync': return cmdSync();
      case 'check': return cmdCheck();
      case 'doctor': return cmdDoctor();
      case 'gate': if (rest[0] === 'set') return cmdGateSet(rest[1], rest[2]); throw new Error('usage: gate set <lint|build|typecheck|test> <pass|fail|count>');
      case 'task': return cmdTask(rest);
      case undefined:
      case 'help':
      case '--help':
        console.log([
          'ai-control <command>',
          '  init [--name "X"] [--branch main] [--code "src,lib"] [--db] [--deploy]   scaffold the control plane',
          '  init --web [--name X] [--spa] [--drizzle] [--deploy-target vercel|netlify|static|none] [--new|--existing]   web preset (Next/Supabase defaults, detects existing stack, wires hooks)',
          '  status   3-axis status summary (taskState · deliveryState · approvalState)',
          '  sync     render current-state|current-focus|tasks .md + worklog event log (below the freeze marker)',
          '  check    deterministic consistency gate (exit != 0 on fail)',
          '  doctor   read-only whole-system health',
          '  task create --id ID --title T [--owner coder|PM] [--mode max|ultracode] [--model …] [--in "a;b"] [--out "a;b"] [--gates "a;b"] [--docs "a,b"]',
          '  task ready|start|accept|block|reopen|abandon <ID>',
          '  task checkpoint <ID> [--note …] [--docs-reviewed a,b] [--docs-changed a,b]',
          '  task finish <ID> [--commit SHA] [--summary …] [--docs-reviewed a,b] [--docs-changed a,b]',
          '  task deliver <ID> <committed|pushed|deployed> [--commit SHA]',
          '  gate set <lint|build|typecheck> <pass|fail>   (internal; exercises atomic write)',
          '',
          'Source of truth: .ai/control/. Generated views: current-state/current-focus/tasks .md + worklog (below marker).',
          'Project specifics: .ai/control/config.json (init) + .ai/PROJECT.md (authored).',
        ].join('\n'));
        return 0;
      default: console.error(`unknown command: ${cmd} (try: help)`); return 2;
    }
  } catch (e) {
    console.error(`ai-control ${cmd}: ERROR — ${e.message}`);
    return 1;
  }
}

process.exit(main());
